services:
  postgres:
    image: postgres:18
    container_name: sedna-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-db_admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - hba_file=/etc/postgresql/pg_hba.conf
    ports:
      - ${POSTGRES_PORT-5437}:5437
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./configs/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./configs/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h 127.0.0.1 -p 5437 -U $${POSTGRES_USER} -d $${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - sedna-network

  sedna-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: sedna-worker
    container_name: sedna-worker
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # UGLS
      API_URL: ${API_URL:-http://localhost:8080/api}
      LOCAL_DATABASE_URL: ${LOCAL_DATABASE_URL:-postgres://admin:password123@postgres:5437/db_admin}
      PROD_DATABASE_URL: ${PROD_DATABASE_URL}

      # TIMES
      TIME_TO_PING: ${TIME_TO_PING:-15}
      TIME_TO_CALC_LATENCY: ${TIME_TO_CALC_LATENCY:-10}
      DELAY_TIME: ${DELAY_TIME:-15}
      TIME_TO_CLEAR_OLD_DATA: ${TIME_TO_CLEAR_OLD_DATA:-4}

      # OPTIONS
      CLEAR_OLD_DATA_ON_START: ${CLEAR_OLD_DATA_ON_START:-true}
      CLEAR_OLD_DATA: ${CLEAR_OLD_DATA:-true}
      SIZE_OF_STATUS_ON_REGISTER: ${SIZE_OF_STATUS_ON_REGISTER:-30}
      END_POINT_OF_REGISTER: ${END_POINT_OF_REGISTER}
      SAVE_DATA_ON_DATABASE: ${SAVE_DATA_ON_DATABASE:-true}
      MIGRATE_ON_RUN: ${MIGRATE_ON_RUN:-false}

      # DEPLOY OPTIONS
      CHECK_FOR_DEPLOYS: ${CHECK_FOR_DEPLOYS:-false}
      TIME_TO_CHECK_FOR_NEW_DEPLOY: ${TIME_TO_CHECK_FOR_NEW_DEPLOY:-5}

      # GITHUB
      APP_GITHUB_OWNE: ${APP_GITHUB_OWNER}
      APP_GITHUB_REPO: ${APP_GITHUB_REPO}
      APP_GITHUB_BRANCH: ${APP_GITHUB_BRANCH:-main}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

      # DEPLOY COMMANDS
      DEPLOY_COMMAND: ${DEPLOY_COMMAND}
      DEPLOY_BRANCH: ${DEPLOY_BRANCH:-main}
      DEPLOY_MESSAGE: ${DEPLOY_MESSAGE:-""}
      DEPLOY_DIR: ${DEPLOY_DIR}
      DEPLOY_BUILD_COMMAND: ${DEPLOY_BUILD_COMMAND}
      DEPLOY_BUILDED_DIR: ${DEPLOY_BUILDED_DIR}

      # DISCORD
      DISCORD_WEBHOOK_USERNAME: ${DISCORD_WEBHOOK_USERNAME:-Sedna Worker}
      USE_DISCORD_WEBHOOKS: ${USE_DISCORD_WEBHOOKS:-true}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}

      # VALUES
      SIZE_OF_HEARTBEATS_TO_CALC_LATENCY: ${SIZE_OF_HEARTBEATS_TO_CALC_LATENCY:-25}
      SIZE_OF_STATUS_DATA_AFTER_CLEAR: ${SIZE_OF_STATUS_DATA_AFTER_CLEAR:-50}

      # DATABASE CONFIG
      POSTGRES_DB: ${POSTGRES_DB:-db_admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password123}

      # BUILD
      EMBEDDED_WORKER: ${EMBEDDED_WORKER:-0}
    networks:
      - sedna-network

networks:
  sedna-network:
    driver: bridge

volumes:
  postgres-data:
