services:
  sedna-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: sedna-worker:v1.1
    container_name: sedna-worker
    restart: unless-stopped
    environment:
      API_URL: ${API_URL}
      LOCAL_DATABASE_URL: ${LOCAL_DATABASE_URL}
    ports:
      - 8000:8000
    networks:
      - sedna-network

networks:
  sedna-network:
    driver: bridge
